name: CI Pipeline

on:
  push:
    branches: 
      - "**" 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Run tests
        run: go test ./...

      - name: Run static analysis
        run: go vet ./...

      - name: Build Docker image
        run: |
          docker build -t neiroc/hello-world-app:latest .
          
      # - name: Scan Docker image for vulnerabilities
      #   run: |
      #     docker run --rm aquasec/trivy:latest image --exit-code 1 --severity HIGH,CRITICAL neiroc/hello-world-app:latest

      - name: Tag Docker image
        run: |
          docker tag neiroc/hello-world-app:latest neiroc/hello-world-app:${{ github.sha }}

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u neiroc --password-stdin

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push neiroc/hello-world-app:latest
          docker push neiroc/hello-world-app:${{ github.sha }}

